package com.blog.dao;

import java.util.List;
import java.util.Map;

import com.blog.model.Article;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Apr 26 10:17:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Apr 26 10:17:06 CST 2017
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Apr 26 10:17:06 CST 2017
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Apr 26 10:17:06 CST 2017
     */
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Apr 26 10:17:06 CST 2017
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Wed Apr 26 10:17:06 CST 2017
     */
    int updateByPrimaryKey(Article record);
    
    List<Article> selectArticleList();
    List<Map<String, Object>> getCommentsByArticleId(Integer id);
}