package com.blog.model;

import java.util.Date;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.title
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.location
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_time
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.update_time
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.is_delete
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.desc
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.temp1
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.temp2
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.temp3
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    private String temp3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.title
     *
     * @return the value of picture.title
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.title
     *
     * @param title the value for picture.title
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.location
     *
     * @return the value of picture.location
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.location
     *
     * @param location the value for picture.location
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_time
     *
     * @return the value of picture.create_time
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_time
     *
     * @param createTime the value for picture.create_time
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.update_time
     *
     * @return the value of picture.update_time
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.update_time
     *
     * @param updateTime the value for picture.update_time
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.is_delete
     *
     * @return the value of picture.is_delete
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.is_delete
     *
     * @param isDelete the value for picture.is_delete
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.desc
     *
     * @return the value of picture.desc
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.desc
     *
     * @param desc the value for picture.desc
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.temp1
     *
     * @return the value of picture.temp1
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.temp1
     *
     * @param temp1 the value for picture.temp1
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.temp2
     *
     * @return the value of picture.temp2
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.temp2
     *
     * @param temp2 the value for picture.temp2
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.temp3
     *
     * @return the value of picture.temp3
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.temp3
     *
     * @param temp3 the value for picture.temp3
     *
     * @mbggenerated Wed Apr 26 10:19:47 CST 2017
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }
}